Auto-detect kernel version

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,15 +17,15 @@ ac_help="$ac_help
 ac_help="$ac_help
   --with-group=GROUP      Set the group owner of installed files "
 ac_help="$ac_help
+  --enable-jobs=NUM       Number of jobs to run simultaneously"
+ac_help="$ac_help
   --with-kernel-dir=DIR   linux kernel source in DIR [/usr/src/linux]"
 ac_help="$ac_help
-  --with-kernel-version=VERSION   linux kernel version [2.4.16]"
+  --with-kernel-version=VERSION   linux kernel version"
 ac_help="$ac_help
   --with-tmp-dir=DIR      temp directory to make kernel patches [/tmp/kerndiff]"
 ac_help="$ac_help
   --with-interface=IFACE  Choose kernel interface (ioctl or fs) [ioctl]"
-ac_help="$ac_help
-  --enable-jobs=NUM       Number of jobs to run simultaneously"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -1610,82 +1610,6 @@ else
 fi
 
 
-# Check whether --with-kerneldir or --without-kerneldir was given.
-if test "${with_kerneldir+set}" = set; then
-  withval="$with_kerneldir"
-   kerneldir="$withval" 
-else
-   kerneldir=/usr/src/linux 
-fi
-
-if test "${with_kernel_dir+set}" = set; then
-   kerneldir="$with_kernel_dir"
-fi
-if test "${with_kernel-dir+set}" = set; then
-   kerneldir="$with_kerneldir"
-fi
-if test "${with_kernel-src+set}" = set; then
-   kerneldir="$with_kernel-src"
-fi
-if test "${with_kernel_src+set}" = set; then
-   kerneldir="$with_kernel_src"
-fi
-if test "${with_kernel+set}" = set; then
-   kerneldir="$with_kernel"
-fi
-
-# Check whether --with-kernel-version or --without-kernel-version was given.
-if test "${with_kernel_version+set}" = set; then
-  withval="$with_kernel_version"
-   kernelvsn="$withval" 
-else
-   kernelvsn=2.4.16 
-fi
-
-if test "${with_kernelvsn+set}" = set; then
-   kernelvsn="$with_kernelvsn"
-fi
-if test "${with_kernel_version+set}" = set; then
-   kernelvsn="$with_kernel_version"
-fi
-if test "${with_kernelversion+set}" = set; then
-   kernelvsn="$with_kernelversion"
-fi
-
-echo "using kernel version $kernelvsn in $kerneldir"
-
-# Check whether --with-tmp-dir or --without-tmp-dir was given.
-if test "${with_tmp_dir+set}" = set; then
-  withval="$with_tmp_dir"
-   tmpdir="$withval" 
-else
-   tmpdir=/tmp/kerneldiffs 
-fi
-
-if test "${with_tmp_dir+set}" = set; then
-   tmpdir="$with_tmp_dir"
-fi
-if test "${with_tmpdir+set}" = set; then
-   tmpdir="$with_tmpdir"
-fi
-
-# Check whether --with-interface or --without-interface was given.
-if test "${with_interface+set}" = set; then
-  withval="$with_interface"
-   interface="$withval" 
-else
-   interface=ioctl 
-fi
-
-if [ "x$interface" != xfs -a "x$interface" != xioctl ];
-then
-  echo
-  echo "Please specify either  --with-interface=ioctl  or --with-interface=fs"
-  exit 1;
-else
-  echo "using $interface interface"
-fi
-
 # Check whether --enable-jobs or --disable-jobs was given.
 if test "${enable_jobs+set}" = set; then
   enableval="$enable_jobs"
@@ -1697,13 +1621,13 @@ fi
 
 if test $ac_cv_prog_gcc = yes; then
     echo $ac_n "checking whether ${CC-cc} needs -traditional""... $ac_c" 1>&6
-echo "configure:1701: checking whether ${CC-cc} needs -traditional" >&5
+echo "configure:1625: checking whether ${CC-cc} needs -traditional" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_gcc_traditional'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
     ac_pattern="Autoconf.*'x'"
   cat > conftest.$ac_ext <<EOF
-#line 1707 "configure"
+#line 1631 "configure"
 #include "confdefs.h"
 #include <sgtty.h>
 Autoconf TIOCGETP
@@ -1721,7 +1645,7 @@ rm -f conftest*
 
   if test $ac_cv_prog_gcc_traditional = no; then
     cat > conftest.$ac_ext <<EOF
-#line 1725 "configure"
+#line 1649 "configure"
 #include "confdefs.h"
 #include <termio.h>
 Autoconf TCGETA
@@ -1743,12 +1667,12 @@ echo "$ac_t""$ac_cv_prog_gcc_traditional" 1>&6
 fi
 
 echo $ac_n "checking return type of signal handlers""... $ac_c" 1>&6
-echo "configure:1747: checking return type of signal handlers" >&5
+echo "configure:1671: checking return type of signal handlers" >&5
 if eval "test \"`echo '$''{'ac_cv_type_signal'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1752 "configure"
+#line 1676 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <signal.h>
@@ -1765,7 +1689,7 @@ int main() {
 int i;
 ; return 0; }
 EOF
-if { (eval echo configure:1769: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1693: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_type_signal=void
 else
@@ -1784,12 +1708,12 @@ EOF
 
 
 echo $ac_n "checking for vprintf""... $ac_c" 1>&6
-echo "configure:1788: checking for vprintf" >&5
+echo "configure:1712: checking for vprintf" >&5
 if eval "test \"`echo '$''{'ac_cv_func_vprintf'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1793 "configure"
+#line 1717 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char vprintf(); below.  */
@@ -1812,7 +1736,7 @@ vprintf();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1816: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1740: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_vprintf=yes"
 else
@@ -1836,12 +1760,12 @@ fi
 
 if test "$ac_cv_func_vprintf" != yes; then
 echo $ac_n "checking for _doprnt""... $ac_c" 1>&6
-echo "configure:1840: checking for _doprnt" >&5
+echo "configure:1764: checking for _doprnt" >&5
 if eval "test \"`echo '$''{'ac_cv_func__doprnt'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1845 "configure"
+#line 1769 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char _doprnt(); below.  */
@@ -1864,7 +1788,7 @@ _doprnt();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1868: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1792: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func__doprnt=yes"
 else
@@ -1891,12 +1815,12 @@ fi
 for ac_func in mkdir rmdir uname
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:1895: checking for $ac_func" >&5
+echo "configure:1819: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1900 "configure"
+#line 1824 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -1919,7 +1843,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1923: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1847: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -1943,6 +1867,90 @@ else
 fi
 done
 
+
+echo $ac_n "checking for kernel directory""... $ac_c" 1>&6
+# Check whether --with-kerneldir or --without-kerneldir was given.
+if test "${with_kerneldir+set}" = set; then
+  withval="$with_kerneldir"
+   kerneldir="$withval" 
+else
+   kerneldir=/usr/src/linux 
+fi
+
+if test "${with_kernel_dir+set}" = set; then
+   kerneldir="$with_kernel_dir"
+fi
+if test "${with_kernel-dir+set}" = set; then
+   kerneldir="$with_kerneldir"
+fi
+if test "${with_kernel-src+set}" = set; then
+   kerneldir="$with_kernel-src"
+fi
+if test "${with_kernel_src+set}" = set; then
+   kerneldir="$with_kernel_src"
+fi
+if test "${with_kernel+set}" = set; then
+   kerneldir="$with_kernel"
+fi
+echo "$ac_t""$kerneldir" 1>&6
+
+test -d $kerneldir || { echo "configure: error: kernel directory $kerneldir not found" 1>&2; exit 1; }
+
+echo $ac_n "checking for kernel version""... $ac_c" 1>&6
+# Check whether --with-kernel-version or --without-kernel-version was given.
+if test "${with_kernel_version+set}" = set; then
+  withval="$with_kernel_version"
+   kernelvsn="$withval" 
+else
+   kernelvsn=`awk -F ' = ' '/^VERSION/ {v=$2} /^PATCH/ {p=$2} /^SUBLEVEL/ {s=$2} END {printf "%d.%d.%d",v,p,s}' $kerneldir/Makefile` 
+fi
+
+if test "${with_kernelvsn+set}" = set; then
+   kernelvsn="$with_kernelvsn"
+fi
+if test "${with_kernel_version+set}" = set; then
+   kernelvsn="$with_kernel_version"
+fi
+if test "${with_kernelversion+set}" = set; then
+   kernelvsn="$with_kernelversion"
+fi
+
+if test "x$kernelvsn" = x; then
+   echo "configure: error: kernel version not found"
+   exit 1
+fi
+echo "$ac_t""$kernelvsn" 1>&6
+
+# Check whether --with-tmp-dir or --without-tmp-dir was given.
+if test "${with_tmp_dir+set}" = set; then
+  withval="$with_tmp_dir"
+   tmpdir="$withval" 
+else
+   tmpdir=/tmp/kerneldiffs 
+fi
+
+if test "${with_tmp_dir+set}" = set; then
+   tmpdir="$with_tmp_dir"
+fi
+if test "${with_tmpdir+set}" = set; then
+   tmpdir="$with_tmpdir"
+fi
+
+echo $ac_n "checking for kernel interface choice""... $ac_c" 1>&6
+# Check whether --with-interface or --without-interface was given.
+if test "${with_interface+set}" = set; then
+  withval="$with_interface"
+   interface="$withval" 
+else
+   interface=ioctl 
+fi
+
+if [ "x$interface" != xfs -a "x$interface" != xioctl ];
+then
+  echo "configure: error: --with-interface=ioctl or --with-interface=fs required" 1>&2
+  exit 1;
+fi
+echo "$ac_t""$interface" 1>&6
 
 
 
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -58,6 +58,15 @@ AC_ARG_WITH(group,
   [ GROUP="$withval" ],
   [ GROUP="root" ])
 
+AC_ARG_ENABLE(jobs, [  --enable-jobs=NUM       Number of jobs to run simultaneously], JOBS=-j$enableval, JOBS=)
+
+dnl Checks for library functions.
+AC_PROG_GCC_TRADITIONAL
+AC_TYPE_SIGNAL
+AC_FUNC_VPRINTF
+AC_CHECK_FUNCS(mkdir rmdir uname)
+
+echo $ac_n "checking for kernel directory""... $ac_c" 1>&6
 dnl -- Where the linux src tree is
 AC_ARG_WITH(kerneldir,
   [  --with-kernel-dir=DIR   linux kernel source in DIR [/usr/src/linux]],
@@ -78,12 +87,16 @@ fi
 if test "${with_kernel+set}" = set; then
    kerneldir="$with_kernel"
 fi
+echo "$ac_t""$kerneldir" 1>&6
 
+test -d $kerneldir || { echo "configure: error: kernel directory $kerneldir not found" 1>&2; exit 1; }
+
+echo $ac_n "checking for kernel version""... $ac_c" 1>&6
 dnl -- Kernel version string
 AC_ARG_WITH(kernel-version,
-  [  --with-kernel-version=VERSION   linux kernel version [2.4.16]],
+  [  --with-kernel-version=VERSION   linux kernel version],
   [ kernelvsn="$withval" ],
-  [ kernelvsn=2.4.16 ])
+  [ kernelvsn=`awk -F ' = ' '/^VERSION/ {v=$2} /^PATCH/ {p=$2} /^SUBLEVEL/ {s=$2} END {printf "%d.%d.%d",v,p,s}' $kerneldir/Makefile` ])
 if test "${with_kernelvsn+set}" = set; then
    kernelvsn="$with_kernelvsn"
 fi
@@ -94,7 +107,11 @@ if test "${with_kernelversion+set}" = set; then
    kernelvsn="$with_kernelversion"
 fi
 
-echo "using kernel version $kernelvsn in $kerneldir"
+if test "x$kernelvsn" = x; then
+   echo "configure: error: kernel version not found"
+   exit 1
+fi
+echo "$ac_t""$kernelvsn" 1>&6
 
 dnl -- Temporary directory for kernel diffs
 AC_ARG_WITH(tmp-dir,
@@ -108,6 +125,7 @@ if test "${with_tmpdir+set}" = set; then
    tmpdir="$with_tmpdir"
 fi
 
+echo $ac_n "checking for kernel interface choice""... $ac_c" 1>&6
 dnl -- which kernel interface to use (ioctl or fs)
 AC_ARG_WITH(interface,
   [  --with-interface=IFACE  Choose kernel interface (ioctl or fs) [ioctl]],
@@ -115,20 +133,10 @@ AC_ARG_WITH(interface,
   [ interface=ioctl ])
 if [[ "x$interface" != xfs -a "x$interface" != xioctl ]];
 then
-  echo
-  echo "Please specify either  --with-interface=ioctl  or --with-interface=fs"
+  echo "configure: error: --with-interface=ioctl or --with-interface=fs required" 1>&2
   exit 1;
-else
-  echo "using $interface interface"
 fi
-
-AC_ARG_ENABLE(jobs, [  --enable-jobs=NUM       Number of jobs to run simultaneously], JOBS=-j$enableval, JOBS=)
-
-dnl Checks for library functions.
-AC_PROG_GCC_TRADITIONAL
-AC_TYPE_SIGNAL
-AC_FUNC_VPRINTF
-AC_CHECK_FUNCS(mkdir rmdir uname)
+echo "$ac_t""$interface" 1>&6
 
 AC_SUBST(JOBS)
 AC_SUBST(OWNER)
